# This config file is used by ros2_control
/**:
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz

      panda_arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      panda_hand_controller:
        type: position_controllers/GripperActionController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster


  panda_arm_controller:
    ros__parameters:
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      joints:
        - franka_1_panda_joint1
        - franka_1_panda_joint2
        - franka_1_panda_joint3
        - franka_1_panda_joint4
        - franka_1_panda_joint5
        - franka_1_panda_joint6
        - franka_1_panda_joint7

  panda_hand_controller:
    ros__parameters:
      joint: franka_1_panda_finger_joint1
