# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  franka_1_panda_joint1: 0.0
  franka_1_panda_joint2: -0.785
  franka_1_panda_joint3: 0.0
  franka_1_panda_joint4: -2.356
  franka_1_panda_joint5: 0.0
  franka_1_panda_joint6: 1.571
  franka_1_panda_joint7: 0.785
