# mapf:
#   map_server:
#     ros__parameters:
#       use_sim_time: true

#   mapf_base_node:
#     ros__parameters:
#       use_sim_time: true
#       agent_num: 2
#       global_frame_id: World
#       planner_time_tolerance: 5.0
#       goal_tolerance: 1.0
#       mapf_planner: "mapf_planner/CBSROS"

#       base_frame_id:
#         agent_0: carter1/nova_carter
#         agent_1: carter2/nova_carter

#       plan_topic:
#         agent_0: carter1/plan
#         agent_1: carter2/plan

#   goal_transformer:
#     ros__parameters:
#       use_sim_time: true
#       agent_num: 2
#       goal_topic:
#         agent_0: carter1/goal
#         agent_1: carter2/goal

mapf:
  map_server:
    ros__parameters:
      use_sim_time: true

  mapf_base_node:
    ros__parameters:
      use_sim_time: true
      agent_num: 1
      global_frame_id: map
      planner_time_tolerance: 5.0
      goal_tolerance: 1.0
      mapf_planner: "mapf_planner/CBSROS"

      base_frame_id:
        agent_0: carter1/chassis_link/base_link

      plan_topic:
        agent_0: carter1/plan

  goal_transformer:
    ros__parameters:
      use_sim_time: true
      agent_num: 1
      goal_topic:
        agent_0: carter1/goal